### ISSUE TITLE
Create 404 Template

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-theme#12]
### Description

Create a 404 template (`404.html`) that contains static text saying that the page can't be found.

### Use Case

> As a user, I want a friendly message if content I was looking for wasn't able to be found.

### Acceptance Criteria

- Create a 404.html template that contains the following fields in this order:
  - [Header](https://github.com/alleyinteractive/create-wordpress-theme/issues/5)
  - H1 that says "Not Found"
  - Paragraph that says "We're sorry, page you're looking for could not be found. Please use your browser's 'Back' button or use one of the navigation links on this page."
  - [Footer](https://github.com/alleyinteractive/create-wordpress-theme/issues/6)
- Establish enough styles in the blocks and/or theme.json to ensure the display is reasonable. The intention is for the 404 template to look like a monochrome version of the 404 view, which will be further customized by theme implementers with colors and fonts, but basic positioning/font size/etc should be set as part of this ticket.

### Technical Details

- Completion of this issue relies on completion of other issues linked in the above list.
- When developing locally, you will need to ensure that the custom blocks, slotfills, postmeta, features, etc that are part of the project template are installed and built in a plugin based on create-wordpress-plugin.
- Use the standard WordPress blocks for the heading and paragraph. All other blocks or template parts are custom and are linked above.

**Comment by ellm** [comment]
Completed in #21
