### ISSUE TITLE
Create Search Template

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-theme#13]
### Description

We need a search template that will include basic faceted search, result counts, a result list, and pagination.

### Use Case

> As a user, I want to be able to search the site and filter by topic and content type.

### Acceptance Criteria

- Create a search.html template that contains the following fields in this order:
  - [Header](https://github.com/alleyinteractive/create-wordpress-theme/issues/5)
  - [Faceted Search Block](https://github.com/alleyinteractive/create-wordpress-project/issues/55)
  - [Footer](https://github.com/alleyinteractive/create-wordpress-theme/issues/6)
- Establish enough styles in the blocks and/or theme.json to ensure the display is reasonable. The intention is for the search template to look like a monochrome version of a search view, which will be further customized by theme implementers with colors and fonts, but basic positioning/font size/etc should be set as part of this ticket.

### Technical Details

- Completion of this issue relies on completion of other issues linked in the above list.
- When developing locally, you will need to ensure that the custom blocks, slotfills, postmeta, features, etc that are part of the project template are installed and built in a plugin based on create-wordpress-plugin. This includes Elasticsearch Extensions for the related content block.

**Comment by kaitlinbolling** [comment]
An initial single post template has been scaffolded. Completion of this issue is blocked until the custom [faceted search block](https://github.com/alleyinteractive/create-wordpress-project/issues/55) is created.
