### ISSUE TITLE
Allow Responsive Image attributes in templates

### ISSUE THREAD

**Issue by ellm** [alleyinteractive/create-wordpress-theme#2]
### Description
By default, WordPress automatically handles responsive images correctly from within the block editor area when inserting a image block. However, image blocks inserted anywhere outside the block editor, `<img>` tag attributes such as `srcset` and `sizes` are stripped away upon output. 

### Use Case
As a custom block theme developer, I'd like to provide optimal image sizes to the browser so it can determine the most performant size to load. Responsive Images should work consistently regardless of the image being displayed from within the block editor or not.

**Comment by kevinfodness** [comment]
@kaitlinbolling can you confirm if this is still true?

**Comment by kaitlinbolling** [comment]
I tested an image block within a post and within a footer template part and I'm seeing the same output, with responsive image attributes in both, so I think this can close.
