### ISSUE TITLE
SVG Support 

### ISSUE THREAD

**Issue by ellm** [alleyinteractive/create-wordpress-theme#3]
### Description 
By default, SVGs are not well supported in themes. When adding SVGs, the markup can be stripped out by `wp_kses` and we need to add relevant HTML to the `filter_wp_kses_allowed_html` . The Alley plugin WP Asset Manager (https://github.com/alleyinteractive/wp-asset-manager) provides good support for working with SVGs but is not currently a dependency.

**Comment by mogmarsh** [comment]
WP Asset Manager will now get installed as part of the create-wordpress-project configure process

**Comment by kevinfodness** [comment]
Since we're expecting folks to use create-wordpress-project, and create-wordpress-project already includes WP Asset Manager as @mogmarsh pointed out, which should provide us with what we need to handle including SVGs in areas like headers, footers, buttons, etc.
