### ISSUE TITLE
Create Single Post Template

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-theme#9]
### Description

Create a single post template (`single.html`) that contains the featured image, featured image caption, primary category as an eyebrow, post title, subheadline, author, publish date, list of tags, post content, and a related content module.

### Use Case

> As an editor, I want to be able to create an article with a common set of fields.

### Acceptance Criteria

- Create a single.html template that contains the following fields in this order:
  - [Header](https://github.com/alleyinteractive/create-wordpress-theme/issues/5)
  - [Featured Image with Caption](https://github.com/alleyinteractive/create-wordpress-project/issues/50)
  - [Primary Category](https://github.com/alleyinteractive/create-wordpress-project/issues/53)
  - Post Title
  - [Subheadline](https://github.com/alleyinteractive/create-wordpress-project/issues/52)
  - [Author](https://github.com/alleyinteractive/byline-manager/issues/74)
  - Publish Date
  - Tag List
  - Post Content
  - [Related Content](https://github.com/alleyinteractive/create-wordpress-project/issues/54)
  - [Footer](https://github.com/alleyinteractive/create-wordpress-theme/issues/6)
- Establish enough styles in the blocks and/or theme.json to ensure the display is reasonable. The intention is for the single template to look like a monochrome version of an article view, which will be further customized by theme implementers with colors and fonts, but basic positioning/font size/etc should be set as part of this ticket.

### Technical Details

- Completion of this issue relies on completion of other issues linked in the above list.
- When developing locally, you will need to ensure that the custom blocks, slotfills, postmeta, features, etc that are part of the project template are installed and built in a plugin based on create-wordpress-plugin. This includes Elasticsearch Extensions for the related content block.
- Use the standard WordPress blocks for post title, publish date, tag list, and post content. All other blocks or template parts are custom and are linked above.

**Comment by kaitlinbolling** [comment]
An initial single post template has been scaffolded. Completion of this issue is blocked until all custom blocks have been created.
